name: 'Bark Action'
description: 'An action for bark'
author: 'Yuanhao Ji <jiyuanhao@apache.org>'
branding:
  icon: 'message-circle'
  color: 'red'
inputs:
  key:
    description: Secret key
    required: true
  host:
    description: Bark server hostname
    required: false
  title:
    description: 'Notification title'
    required: false
  subtitle:
    description: 'Notification subtitle'
    required: false
  body:
    description: 'Notification body'
    required: false
  level:
    description: 'Notification level (active, timeSensitive, passive)'
    required: false
    default: 'active'
  badge:
    description: 'Badge number'
    required: false
  autoCopy:
    description: 'Enable auto-copy on iOS <14.5'
    required: false
  copy:
    description: 'Specify content to copy'
    required: false
  sound:
    description: 'Notification sound'
    required: false
  call:
    description: 'Repeat notification sound'
    required: false
  icon:
    description: 'Custom notification icon URL'
    required: false
  group:
    description: 'Notification group'
    required: false
  ciphertext:
    description: 'Enable encryption for push content'
    required: false
  volume:
    description: 'Notification sound volume'
    required: false
  isArchive:
    description: 'Save the push (1 to save, leave empty to use app default)'
    required: false
  url:
    description: 'URL to open when clicking notification'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Run script
      shell: bash
      run: $GITHUB_ACTION_PATH/script.sh
      env:
        INPUT_KEY: ${{ inputs.key }}
        INPUT_HOST: ${{ inputs.host }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_SUBTITLE: ${{ inputs.subtitle }}
        INPUT_BODY: ${{ inputs.body }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_BADGE: ${{ inputs.badge }}
        INPUT_AUTOCOPY: ${{ inputs.autoCopy }}
        INPUT_COPY: ${{ inputs.copy }}
        INPUT_SOUND: ${{ inputs.sound }}
        INPUT_CALL: ${{ inputs.call }}
        INPUT_ICON: ${{ inputs.icon }}
        INPUT_GROUP: ${{ inputs.group }}
        INPUT_CIPHERTEXT: ${{ inputs.ciphertext }}
        INPUT_VOLUME: ${{ inputs.volume }}
        INPUT_ISARCHIVE: ${{ inputs.isArchive }}
        INPUT_URL: ${{ inputs.url }}